### ISSUE TITLE
移动端怎么不开源？有开源计划吗

### ISSUE THREAD

**Issue by gang0713** [macrozheng/mall-swarm#106]
移动端怎么不开源？有开源计划吗

**Comment by aaa7636602** [comment]
有的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ss ***@***.***&gt;
发送时间: 2022年4月8日 16:48
收件人: macrozheng/mall-swarm ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [macrozheng/mall-swarm] 手机端怎么不开源？有开源计划吗 (Issue #106)





 
手机端怎么不开源？有开源计划吗

**Comment by izifeng** [comment]
请问移动端项目是那个呢
