### ISSUE TITLE
info接口取不到用户

### ISSUE THREAD

**Issue by xiaoyuexiao** [macrozheng/mall-swarm#114]
![image](https://user-images.githubusercontent.com/22761557/174938188-ae7f91a3-a4dd-495e-addf-b8b6d0326235.png)
![image](https://user-images.githubusercontent.com/22761557/174938208-8a400b0d-cfc1-47a8-a0e3-6c44a22956d5.png)

**Comment by XiaoSong2017** [comment]
我在用该项目的前端与微服务后端进行调试时也遇到过类似的问题，根据排查，发现需要将前端项目的访问路径前添加上mall-xxx对应微服务模块的名称就能修复，希望能对你有所帮助！！
![image](https://user-images.githubusercontent.com/35443773/175187624-338a1539-1e4e-4809-9c8b-b42e57db03a8.png)

**Comment by developer-wlj** [comment]
> 我在用该项目的前端与微服务后端进行调试时也遇到过类似的问题，根据排查，发现需要将前端项目的访问路径前添加上mall-xxx对应微服务模块的名称就能修复，希望能对你有所帮助！！ ![image](https://user-images.githubusercontent.com/35443773/175188222-63b18d70-8e68-4b3f-967f-c3ac941a421b.png)

感谢老哥,  我说下自己本地调试遇到的问题, 拉取的前端代码是直接访问相关微服务,没经过网关接口, 而且前端没配置代理, 直接访问的接口, 造成前后端跨域, 后端这块 只有网关有配置全局跨域 ,说白了 两种方案,1 向老哥说的 改前端代码 走网关 改路径和端口 2 其他后端模块也配置上全局跨域,
