### ISSUE TITLE
网关oauth资源服务异常拦截问题

### ISSUE THREAD

**Issue by pxniu** [macrozheng/mall-swarm#124]
.accessDeniedHandler(restfulAccessDeniedHandler)//处理未授权
.authenticationEntryPoint(restAuthenticationEntryPoint)//处理未认证

这两个是不是应该放到.oauth2ResourceServer()后

**Comment by taozai123** [comment]
> .accessDeniedHandler(restfulAccessDeniedHandler)//处理未授权 .authenticationEntryPoint(restAuthenticationEntryPoint)//处理未认证
> 
> 这两个是不是应该放到.oauth2ResourceServer()后

不用，这两个是security拦截
