### ISSUE TITLE
配置文件不统一

### ISSUE THREAD

**Issue by miaopass-future** [macrozheng/mall-swarm#125]
- 部分项目时从nacos获取配置，部分不是，如mall-monitor时从本地获取的配置文件，项目中也无法配置成从nacos中获取配置文件，因为该项目无法在启动时先加载bootstrap.yml，导致无法再次配置nacos服务地址，继而启动报错，只能从本地获取配置。
- 项目的config目录下有五个服务的配置文件，和对应的项目下的application.yml的配置不相同，例如mall-admin项目等，config目录下的配置文件和服务数量不统一

既然服务已经拆分为微服务，通过nacos获取对应配置，那项目中的application.yml配置就不应该存在，统一在config下维护。

如果是多配置文件，那各个配置文件就不应该出现相同配置，依靠配置加载覆盖，配置起来很迷

**Comment by taozai123** [comment]
> * 部分项目时从nacos获取配置，部分不是，如mall-monitor时从本地获取的配置文件，项目中也无法配置成从nacos中获取配置文件，因为该项目无法在启动时先加载bootstrap.yml，导致无法再次配置nacos服务地址，继而启动报错，只能从本地获取配置。
> * 项目的config目录下有五个服务的配置文件，和对应的项目下的application.yml的配置不相同，例如mall-admin项目等，config目录下的配置文件和服务数量不统一
> 
> 既然服务已经拆分为微服务，通过nacos获取对应配置，那项目中的application.yml配置就不应该存在，统一在config下维护。
> 
> 如果是多配置文件，那各个配置文件就不应该出现相同配置，依靠配置加载覆盖，配置起来很迷

@miaopass-future config文件夹下的配置文件可以上传到nacos配置中心管理，项目下面的配置文件可不用，至于配置文件里面的参数，按照需求自行配置就行
