### ISSUE TITLE
有人遇到在mall-admin-web 通过gateway请求后台接口出现跨域问题么？

### ISSUE THREAD

**Issue by tolower** [macrozheng/mall-swarm#13]
我是在gateway里加了webflux的cors，然后禁掉了mall-admin的GlobalCorsConfig里的配置，才能正常请求，没找着作者是否有相关的说明文档或者处理办法……

**Comment by macrozheng** [comment]
确实存在该问题，可以参考下这个：[前后端分离项目，引入Spring Cloud Gateway遇到的一个问题！](https://juejin.im/post/5e13248e5188253ab849d125)
