### ISSUE TITLE
maven package 报错

### ISSUE THREAD

**Issue by thisinme** [macrozheng/mall-swarm#137]
Expected a com.google.gson.JsonObject **but was com.google.gson.JsonPrimitive**

**Comment by thisinme** [comment]
![image](https://github.com/macrozheng/mall-swarm/assets/69622784/cd11eea1-e444-4ecc-879f-0d314931af58)

**Comment by shuihuaWu** [comment]
这个问题应该是dockerHost配置问题，将dockerHost配置为你的docker私服地址:2375，例如http://192.168.0.1:2375
私服docker开放2375端口请参考：https://www.ngui.cc/el/3066291.html?action=onClick
