### ISSUE TITLE
没有菜单表吗

### ISSUE THREAD

**Issue by liupantao** [macrozheng/mall-swarm#15]
![image](https://user-images.githubusercontent.com/42514934/75141928-f4797700-572c-11ea-952c-9c2ffeb25d8f.png)

/admin/info 接口  官网上返回的有menus数据，本地代码返回值未放menu这个数据

**Comment by ybak** [comment]
遇到了同样的问题。 猜是作者没有更新mall-swarm，适配前端的变更。

**Comment by macrozheng** [comment]
已经更新了
