### ISSUE TITLE
作者有分拆mall-admin成微服务的计划吗？

### ISSUE THREAD

**Issue by ybak** [macrozheng/mall-swarm#18]
这个项目真是个好项目，给作者点个赞。 但是电商核心这块还是个单体服务，没有发挥出微服务基础组件（比如，注册中心，网关）的最大威力。 请问作者后续是否有对电商核心分拆微服务的规划？ 我看到内部已经有cms, oms,pms,sms,ums等模块了。

**Comment by jianjustin** [comment]
微服务不是对细化业务粒度实现解耦吗？这个项目本质还是单体应用吧？请各位大佬明示

**Comment by xueshuai0922** [comment]
这项目确实没有实现为服务本质，我觉得，单纯的业务功能和其他功能分开了，商品搜索es还是在demo里写的，估计博主后续还会持续更新

**Comment by ZainZhao** [comment]
感觉目前mall-swarm还是没有拆分业务，前段时间我模仿mall的技术做了一个[his](https://github.com/ZainZhao/HIS)，把service业务分开了，但也还没有拆库。真正的微服务肯定是要拆库拆业务的

**Comment by SaulJWu** [comment]
> 感觉目前mall-swarm还是没有拆分业务，前段时间我模仿mall的技术做了一个[his](https://github.com/ZainZhao/HIS)，把service业务分开了，但也还没有拆库。真正的微服务肯定是要拆库拆业务的

学习了

**Comment by jaceding** [comment]
> 感觉目前mall-swarm还是没有拆分业务，前段时间我模仿mall的技术做了一个[his](https://github.com/ZainZhao/HIS)，把service业务分开了，但也还没有拆库。真正的微服务肯定是要拆库拆业务的

问个问题，这个项目中实际上没有检验token的逻辑，想问下这部分要咋搞
