### ISSUE TITLE
系统架构图 看不到啊  

### ISSUE THREAD

**Issue by FireAny** [macrozheng/mall-swarm#27]

**Comment by 350679778** [comment]
那个是processon文件
https://www.processon.com/
在这里面导入就可以看了

**Comment by sqskg** [comment]
https://camo.githubusercontent.com/434fab34e097305fc3391e9a16ee5a410840c79a/687474703a2f2f696d672e6d6163726f7a68656e672e636f6d2f6d616c6c2f70726f6a6563742f6d616c6c5f6d6963726f5f736572766963655f617263682e6a7067

![image](https://user-images.githubusercontent.com/14267002/87744481-27c4bb80-c81e-11ea-8d24-f2bdba25a292.png)
