### ISSUE TITLE
关于鉴权

### ISSUE THREAD

**Issue by ZainZhao** [macrozheng/mall-swarm#3]
请问mall-swarm有单独的鉴权服务吗？还是在gateway上用jwt统一鉴权？

**Comment by macrozheng** [comment]
目前是在每个应用里面单独鉴权。

**Comment by ZainZhao** [comment]
那是用什么共享session呢

**Comment by Huangjiaqi0421** [comment]
想问一下，后期会使用zuul来做鉴权么

**Comment by KupoGu** [comment]
都是独立的服务，没有关联,业务无往来，何来共享session?

**Comment by KupoGu** [comment]
关于鉴权认证，楼主的掘金文章里面关于oauth2的有样本，mall整个微服务架构只是一个思想，要商用或者生产还有很大差距

**Comment by ZainZhao** [comment]
我的意思是mall各个服务之间怎样共享鉴权的session，一个人登录之后，不得可以访问多个服务吗？还是在服务的网关进行鉴权，然后调用前置服务admin和portal，然后前置服务再调用底层的服务

**Comment by 37687389** [comment]
> 那是用什么共享session呢

用redis

**Comment by jaceding** [comment]
> 关于鉴权认证，楼主的掘金文章里面关于oauth2的有样本，mall整个微服务架构只是一个思想，要商用或者生产还有很大差距

貌似没有检验token是否有效，随便输入一个token就能通过
