### ISSUE TITLE
gateway

### ISSUE THREAD

**Issue by ArdenCHan** [macrozheng/mall-swarm#32]
gateway，对于这个项目没有任何拦截功能阿，不清楚作者写这个网关是做什么，只是为了解决跨域吗？

**Comment by oldma12138** [comment]
部署的时候可以只开放网关端口，这样访问只能访问到网关，其他服务端口不开放就行了，而且一般会通过网关携带持久化参数

**Comment by ArdenCHan** [comment]
> 部署的时候可以只开放网关端口，这样访问只能访问到网关，其他服务端口不开放就行了，而且一般会通过网关携带持久化参数

我知道这个，我说的是在mall-gateway这个服务中，没有起到拦截，应该是作者没有写

**Comment by KURO-LIANG** [comment]
人家只是做个demo，学习用的

发送来自 梁庆

**Comment by lanseyu05** [comment]
> gateway，对于这个项目没有任何拦截功能阿，不清楚作者写这个网关是做什么，只是为了解决跨域吗？

应该是AuthGlobalFilter这个filter逻辑写错了

**Comment by HatherP** [comment]
ResourceServerConfig验证JWTtoken，AuthorizationManager判断权限

**Comment by jaceding** [comment]
请问下，哪段代码检验了JWTtoken了呢？我测试发现只要请求头有值就能访问到，不管token是否正确
