### ISSUE TITLE
前端登录被自动登出

### ISSUE THREAD

**Issue by zuozewei** [macrozheng/mall-swarm#36]
抓包结果如下：
```
{"code":401,"message":"暂未登录或token已经过期","data":null}
```
![image](https://user-images.githubusercontent.com/17716626/90714590-9e9c1b00-e2da-11ea-85d3-5ec1dbcea6c8.png)

![image](https://user-images.githubusercontent.com/17716626/90714595-a22fa200-e2da-11ea-9c3e-4accc24665c9.png)
![image](https://user-images.githubusercontent.com/17716626/90714607-a52a9280-e2da-11ea-8269-05545676d66c.png)

**Comment by zuozewei** [comment]
> 你在gateway配置里把- "/mall-admin/admin/info"注视掉就可以了，因为admin/info的逻辑是需要鉴权的，此处被添加到了白名单，他在IgnoreUrlsRemoveJwtFilter里把白名单的url强制将Authorization设置为空值
> 导致后面不会走添加"user"这个请求头的逻辑,导致mall-admin里压根获取不到用户;

多谢回复，我按照你说的地方做了调整，不过貌似还是不行。

**Comment by cqkj1226** [comment]
我也是，还是不行

**Comment by macrozheng** [comment]
确实需要去除Gateway中的`/mall-admin/admin/info`配置，该问题已修复，使用最新版代码并导入最新sql文件即可。

**Comment by 12345ZMTHL** [comment]
老哥怎么解决的，我看了白名单里没有admin/info配置，代码和SQL都是最新的，还是会出现这个问题
