### ISSUE TITLE
AuthGlobalFilter的token解析逻辑

### ISSUE THREAD

**Issue by lanseyu05** [macrozheng/mall-swarm#38]
if (StrUtil.isEmpty(token)) {
            return chain.filter(exchange);
        }
        try {
            //从token中解析用户信息并设置到Header中去
            String realToken = token.replace(AuthConstant.JWT_TOKEN_PREFIX, "");
            JWSObject jwsObject = JWSObject.parse(realToken);

这段逻辑感觉不对劲，是我理解错误吗？

**Comment by 18672675036** [comment]
> 其实我都不是很明白token这里为什么要用到RSA加密，jwt本身就带了签名，为什么还要套一层RSA加密来防篡改呢，多此一举了

你再搞笑吧？jwt本身的token签名是很简单的，当然你也可以实现同样的RSA加解密，但是，融入了oauth2之后不一样了。需要更加安全的token保障

**Comment by macrozheng** [comment]
你可以好好看下这篇文章[《听说你的JWT库用起来特别扭，推荐一款贼好用的！》](https://juejin.im/post/6847902224325345288)

**Comment by lanseyu05** [comment]
> 你可以好好看下这篇文章[《听说你的JWT库用起来特别扭，推荐一款贼好用的！》](https://juejin.im/post/6847902224325345288)

public String replace(char oldChar,char newChar)

if (StrUtil.isEmpty(token)) 
改成if (! StrUtil.isEmpty(token))   


String realToken = token.replace(AuthConstant.JWT_TOKEN_PREFIX, "");
改成String realToken = token.replace( ""，AuthConstant.JWT_TOKEN_PREFIX);

不是这样吗？
