### ISSUE TITLE
gateway整合oauth2问题

### ISSUE THREAD

**Issue by HatherP** [macrozheng/mall-swarm#40]
这套方案很不错，请教一下如果我想把auth认证服务器功能放在gateway处可以吗？  也就是说mall-auth和mall-gateway模块整合成一个模块，达到认证、鉴权、网关路由在一个模块里面的效果。

**Comment by dlhf** [comment]
auth需要连接mysql，springgateway是reactor架构，现在的r2dbc倒是提供了连接方案，你可以自己尝试，但不建议到生产

**Comment by stanleysct** [comment]
前端一直登录不了 报错 暂末登入或token已过期，请问要如何解决？
