### ISSUE TITLE
开发环境启动，无法登陆，无解了

### ISSUE THREAD

**Issue by cqkj1226** [macrozheng/mall-swarm#44]
![image](https://user-images.githubusercontent.com/43141782/91189550-26dc4f00-e725-11ea-8e8f-f10cb2e07668.png)
![image](https://user-images.githubusercontent.com/43141782/91189855-876b8c00-e725-11ea-92f5-fc3ec0903908.png)

谁能解答下，或者是说下，真不能跑起来，我也就不去折腾了

**Comment by shenhong74ww** [comment]
我也遇到了类似的问题，我发现作者前端项目的dev.env.js下的请求地址是http://localhost:8080，直接请求登录会报跨域的问题，因为swarm项目gateway地址是http://localhost:8201，当我改成http://localhost:8201后，会报你这个问题，原因是gateway下的mall-admin服务路由规则需要前缀mall-admin，然后请求地址改成http://localhost:8201/mall-admin就可以访问了。我不知道你是否遇到了和我一样的问题，希望能帮你解决。

**Comment by cqkj1226** [comment]
这个修改过，还是不行，应该是PC端的前端有问题。我没去研究了，放弃了。

**Comment by stanleysct** [comment]
我也是遇到同样的问题
