### ISSUE TITLE
大佬求助？

### ISSUE THREAD

**Issue by Zostana** [macrozheng/mall-swarm#46]
最新的微服务的部署文档， 说将配置文档上传到nacos，说的比较模糊，而且截图里面的文件和现在项目实际文件也对不上，能否详细说面下，哪些配置文件需要上传到配置中心？  求教啊

**Comment by macrozheng** [comment]
仔细看部署文档[《mall-swarm在Windows环境下的部署》](http://www.macrozheng.com/#/deploy/mall_swarm_deploy_windows)，截图和配置文件是对应的。
