### ISSUE TITLE
启动报错 Closing connections idle longer than 60000 MILLISECONDS

### ISSUE THREAD

**Issue by qinguabao** [macrozheng/mall-swarm#50]
数据库 redis 都配置了，但是启动 mall-admin还是一直报错
 Closing expired connections
Closing connections idle longer than 60000 MILLISECONDS
不知道 还需要配置 哪里 ？
麻烦 帮忙看看  是什么问题

**Comment by TwiA** [comment]
老铁这是怎么回事啊，同样的问题

**Comment by liuqi1024** [comment]
@ qinguabao 请问是怎么解决的？我也遇到同样的问题了，谢谢！启动mall-admin的时候。

**Comment by liuqi1024** [comment]
> http://localhost:8080/swagger-ui.html

@ qinguabao 请问是怎么解决的？我也遇到同样的问题了，谢谢！启动mall-admin的时候。

**Comment by 1422655169** [comment]
这个不是报错,是因为你使用ossClient使用之后没有关闭,ossClient.shutdown();
