### ISSUE TITLE
通过Outh2认证中心登录接口获得的token总是提示401未认证的错误

### ISSUE THREAD

**Issue by InnovationLou** [macrozheng/mall-swarm#57]
无论是Auth服务中的认证接口还是admin中的登录接口，登录均可成功，但是取得的token请求其他任意接口均报401
`{
  "code": 401,
  "data": "Not Authenticated",
  "message": "暂未登录或token已经过期"
}`

**Comment by DemonsPan** [comment]
> 无论是Auth服务中的认证接口还是admin中的登录接口，登录均可成功，但是取得的token请求其他任意接口均报401
> `{ "code": 401, "data": "Not Authenticated", "message": "暂未登录或token已经过期" }`

我也遇到这个问题了

**Comment by DemonsPan** [comment]
在Authorization前加上Bearer (Bearer+空格),问题解决
