### ISSUE TITLE
模块之间的依赖关系.

### ISSUE THREAD

**Issue by Sunknight945** [macrozheng/mall-swarm#6]
还有鉴权这一块. SpringSecurit 我看着鉴权的那一块感觉太糊了. 我从 您 mall-learing 弄完后过来的, 还是有不清楚的地方..

**Comment by macrozheng** [comment]
你可以看下这些：
- [mall整合SpringSecurity和JWT实现认证和授权（一）](https://juejin.im/post/5cf90fa5e51d455d6d5357d3)
- [mall整合SpringSecurity和JWT实现认证和授权（二）](https://juejin.im/post/5cfa0933f265da1b8f1ab2da)
- [仅需四步，整合SpringSecurity+JWT实现登录认证 ！](https://juejin.im/post/5df0e79bf265da33dd2f52af)
