### ISSUE TITLE
security.oauth2.resourceserver.jwt.jwk-set-uri负载均衡问题？

### ISSUE THREAD

**Issue by 982186883** [macrozheng/mall-swarm#69]
1、如果mail-auth启动多个实例，mall-gateway中的security.oauth2.resourceserver.jwt.jwk-set-uri="http://localhost:8201/mall-auth/rsa/publicKey"是如何保证负载均衡的？
2、mall-gateway中是如何去校验token是否已经注销的？

**Comment by macrozheng** [comment]
这里设置的是从网关访问JWT公钥的路径，网关访问本来就是负载均衡的。关于JWT的token校验问题可以参考#70。
