### ISSUE TITLE
貌似没有检验token是否有效，随便输入一个token就能通过？

### ISSUE THREAD

**Issue by jaceding** [macrozheng/mall-swarm#70]
网关貌似只判断token是否存在，没有校验token是否正确，虽然项目中配置了公钥的地址，但是没有使用到，想问下大佬有没有可以参考的代码来校验token？

**Comment by juziia** [comment]
> 网关貌似只判断token是否存在，没有校验token是否正确，虽然项目中配置了公钥的地址，但是没有使用到，想问下大佬有没有可以参考的代码来校验token？

在配置文件中就可以看到公钥的访问地址，虽然我翻遍了源码也没有看到是在哪里访问并获取的公钥，但是确实是使用了公钥解析的token，你可以尝试使用postman请求接口故意携带错的token访问，是无效的！

**Comment by NicholasHwang** [comment]
用到了公钥的验证，具体流程是AuthenticationWebFilter.authenticate()->JwtReactiveAuthenticationManager.authenticate()->NimbusReactiveJwtDecoder.decode()，这一步会创建一个ReactiveRemoteJWKSource的对象，它会判断自身对象中的JWK缓存是否有东西，没有就会去security.oauth2.resourceserver.jwt.jwk-set-uri指向的rest接口请求，后续会在signedJWT.verify这步来验证，如果验证通过，那么将signedJWT的state从signed修改为verified

**Comment by macrozheng** [comment]
网关中使用`nimbus-jose-jwt`库对token进行了验证，流程基本就是楼上所说的那样。具体可以参考下下面两篇文章：
- [《听说你的JWT库用起来特别扭，推荐一款贼好用的！》](http://www.macrozheng.com/#/reference/jose_jwt_start)
- [《通过DEBUG找出Oauth2自定义处理结果的最佳方案！》](http://www.macrozheng.com/#/reference/my_debug_skill)
