### ISSUE TITLE
请教楼主，移动app的代码仓库发布开源了吗？

### ISSUE THREAD

**Issue by gavinju** [macrozheng/mall-swarm#72]
请教楼主，移动app的代码仓库发布开源了吗？

**Comment by aaa7636602** [comment]
木有，就一个原型吧。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GavinJu"<notifications@github.com&gt;; 
发送时间: 2021年1月26日(星期二) 上午7:36
收件人: "macrozheng/mall-swarm"<mall-swarm@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [macrozheng/mall-swarm] 请教楼主，移动app的代码仓库发布开源了吗？ (#72)





 
请教楼主，移动app的代码仓库发布开源了吗？
