### ISSUE TITLE
提个购物车相关的问题！

### ISSUE THREAD

**Issue by juziia** [macrozheng/mall-swarm#74]
这个项目是非常不错的，但是我有一点疑问！就是购物车这一块的技术实现，在此项目中，购物车中的数据是存在于mysql中的，但是我看过一些其他项目是使用的redis来存储， 使用redis存储优点就是访问高效，能够承受更高的并发，但是却有数据不一致的问题， 比如价格的调整，商品名称的修改等等问题。使用mysql的好处就是数据一致性好，但是由于mysql的并发性能不太好，可能会在大规模的访问情况下导致mysql服务宕机，两个方案有利有弊 ! 不知道各位是如何实现的购物车， 或者有其他的解决方案呢？

**Comment by aaa7636602** [comment]
都可以 ，看你自己的业务体量



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "juziia"<notifications@github.com&gt;; 
发送时间: 2021年2月5日(星期五) 中午12:40
收件人: "macrozheng/mall-swarm"<mall-swarm@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [macrozheng/mall-swarm] 提个购物车相关的问题！ (#74)





 
这个项目是非常不错的，但是我有一点疑问！就是购物车这一块的技术实现，在此项目中，购物车中的数据是存在于mysql中的，但是我看过一些其他项目是使用的redis来存储， 使用redis存储优点就是访问高效，能够承受更高的并发，但是却有数据不一致的问题， 比如价格的调整，商品名称的修改等等问题。使用mysql的好处就是数据一致性好，但是由于mysql的并发性能不太好，可能会在大规模的访问情况下导致mysql服务宕机，两个方案有利有弊 ! 不知道各位是如何实现的购物车， 或者有其他的解决方案呢？

**Comment by juziia** [comment]
> 都可以 ，看你自己的业务体量
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "juziia"<notifications@github.com&gt;; 发送时间: 2021年2月5日(星期五) 中午12:40 收件人: "macrozheng/mall-swarm"<mall-swarm@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [macrozheng/mall-swarm] 提个购物车相关的问题！ (#74) 这个项目是非常不错的，但是我有一点疑问！就是购物车这一块的技术实现，在此项目中，购物车中的数据是存在于mysql中的，但是我看过一些其他项目是使用的redis来存储， 使用redis存储优点就是访问高效，能够承受更高的并发，但是却有数据不一致的问题， 比如价格的调整，商品名称的修改等等问题。使用mysql的好处就是数据一致性好，但是由于mysql的并发性能不太好，可能会在大规模的访问情况下导致mysql服务宕机，两个方案有利有弊 ! 不知道各位是如何实现的购物车， 或者有其他的解决方案呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢
