### ISSUE TITLE
docker-maven-plugin <entryPoint>

### ISSUE THREAD

**Issue by wangtao-aganyun** [macrozheng/mall-swarm#76]
打包的镜像以后,执行docker-compose-app文件,发现项目没有使用nacos配置,数据库链接还是用"localhost:3306"

**Comment by macrozheng** [comment]
在Nacos中需要添加`prod`环境的配置，比如`mall-admin-prod.yaml`，然后打包的时候pom.xml中的<entryPoint>中有`-Dspring.profiles.active=prod`才可以访问。

**Comment by wangtao-aganyun** [comment]
"-Dspring.profiles.active=prod" 在<entryPoint>标签中,感觉启动时没有执行到.

**Comment by wangtao-aganyun** [comment]
<entryPoint>中

**Comment by wangtao-aganyun** [comment]
<entryPoint></entryPoint>

**Comment by wangtao-aganyun** [comment]
"<entryPoint></entryPoint>"

**Comment by wangtao-aganyun** [comment]
entryPoint标签
