### ISSUE TITLE
前端登录自动登出

### ISSUE THREAD

**Issue by WEHOOK** [macrozheng/mall-swarm#79]
将前端项目的地址改为本地网关地址
![image](https://user-images.githubusercontent.com/24522145/111275112-c127c400-8670-11eb-9b9b-e1db65a3cf21.png)
然后登录系统
![image](https://user-images.githubusercontent.com/24522145/111275224-e74d6400-8670-11eb-983e-57c3fdb18be7.png)

![image](https://user-images.githubusercontent.com/24522145/111275196-ddc3fc00-8670-11eb-84c3-37feee2718c7.png)
请问应该怎么解决？

**Comment by WEHOOK** [comment]
已解决，将前端项目里的地址改为
![image](https://user-images.githubusercontent.com/24522145/111580177-1d662180-87f2-11eb-8f06-ab3a8413c7e7.png)

**Comment by aaa7636602** [comment]
刚入手这个项目吗...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "macrozheng/mall-swarm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 中午1:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [macrozheng/mall-swarm] 前端登录自动登出 (#79)





 
已解决，将前端项目里的地址改为
