### ISSUE TITLE
mall-gateway和mall-security为何发布不到centos的docker上去?是我打开方式不正确吗?

### ISSUE THREAD

**Issue by Cekerel** [macrozheng/mall-swarm#9]
![image](https://user-images.githubusercontent.com/34343884/70850680-12726200-1ec8-11ea-9336-57a43cccd2f4.png)
![image](https://user-images.githubusercontent.com/34343884/70850735-ae03d280-1ec8-11ea-923e-0f136a5b511e.png)

**Comment by macrozheng** [comment]
mall-security是个工具模块，不需要发布上去，mall-gateway原来没加docker的maven插件，现在加上了。
